# Generated by Django 2.2 on 2019-06-20 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasesClassify',
            fields=[
                ('diseaseVariety', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('diseaseIntroduce', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EatStatistics',
            fields=[
                ('eatTime', models.DateField(auto_created=True, max_length=100)),
                ('eatId', models.IntegerField(auto_created=True, max_length=20, primary_key=True, serialize=False)),
                ('eatHot', models.IntegerField(max_length=20, null=True)),
                ('eatProtein', models.IntegerField(max_length=20, null=True)),
                ('eatSugar', models.IntegerField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('foodId', models.IntegerField(auto_created=True, max_length=50, primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=100)),
                ('foodMaterial', models.CharField(max_length=200)),
                ('foodHot', models.IntegerField(max_length=20)),
                ('foodProtein', models.IntegerField(max_length=20)),
                ('foodSugar', models.IntegerField(max_length=20)),
                ('foodIntroduce', models.TextField(max_length=200)),
                ('foodUrl', models.URLField()),
                ('diseaseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.DiseasesClassify')),
            ],
        ),
    ]
