# Generated by Django 2.2 on 2019-06-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasesclassify',
            name='diseaseIntroduce',
            field=models.TextField(max_length=1000),
        ),
    ]
