# Generated by Django 2.2 on 2019-06-20 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190620_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='diseaseName',
            new_name='diseaseVariety',
        ),
    ]
