# Generated by Django 2.2 on 2019-06-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190620_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatstatistics',
            name='eatTime',
            field=models.CharField(max_length=100),
        ),
    ]
