# Generated by Django 2.2 on 2019-06-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190620_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatstatistics',
            name='eatHot',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eatstatistics',
            name='eatProtein',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='eatstatistics',
            name='eatSugar',
            field=models.IntegerField(max_length=20),
        ),
    ]
