# Generated by Django 2.2 on 2019-06-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190620_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatstatistics',
            name='eatHot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eatstatistics',
            name='eatId',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eatstatistics',
            name='eatProtein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eatstatistics',
            name='eatSugar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foods',
            name='foodHot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foods',
            name='foodId',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foods',
            name='foodProtein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foods',
            name='foodSugar',
            field=models.IntegerField(),
        ),
    ]
