# Generated by Django 2.2 on 2019-06-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190620_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatS',
            fields=[
                ('eatId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('eatHot', models.IntegerField()),
                ('eatProtein', models.IntegerField()),
                ('eatSugar', models.IntegerField()),
                ('eatTime', models.CharField(max_length=100)),
            ],
        ),
    ]
