# Generated by Django 2.2 on 2019-06-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_eats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EatS',
        ),
    ]
